# Generated by Django 3.1b1 on 2020-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Middle Name'),
        ),
    ]
