# Generated by Django 3.1b1 on 2020-06-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200625_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='users.employee', verbose_name='Employee'),
        ),
    ]
