# Generated by Django 3.0.7 on 2020-08-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('year_graduated', models.CharField(max_length=50, verbose_name='Year Graduated')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact No.')),
                ('relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relation')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact No.')),
                ('address', models.TextField(verbose_name='Adress')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Date Ended')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='employees.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work Histories',
            },
        ),
    ]
