# Generated by Django 3.0.7 on 2020-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200626_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_started',
            field=models.DateField(blank=True, null=True, verbose_name='Date Started'),
        ),
    ]
