version: 2.1
orbs:
  slack: circleci/slack@4.1.2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:11-postgis
        environment:
          PIPENV_VENV_IN_PROJECT: true
          PG_HOST: localhost
          PG_DB:   circle_test
          PG_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      - DATABASE_URL: "postgres://postgres@localhost:5432/circle_test"
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run python manage.py test
      - slack/notify:
          template: success_tagged_deploy_1
          event: always
      # - slack/notify:
      #     event: fail
      #     template: basic_fail_1
workflows:
  deploy_and_notify:
    jobs:
      - build:
          context: 
            - slack-secrets