version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv shell
            python3 manage.py test