version: 2.1
orbs:
  slack: circleci/slack@4.1.2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_fail_1
        
workflows:
  deploy_and_notify:
    jobs:
      - build:
          context: slack-secrets