version: 2.1
orbs:
  slack: circleci/slack@4.1.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv shell
            python3 manage.py test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_fail_1
        
workflows:
  deploy_and_notify:
    jobs:
      - build:
          context: slack-secrets