version: 2.1
orbs:
  slack: circleci/slack@4.1.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:9.6.2
        auth:
          username: mugna_hr
          password: $DOCKERHUB_PASSWORD
        environment:
          DATABASE_URL: postgresql://root@localhost/mugna_hr_test/
    steps:
      - checkout
      - run:
          name: install dependencies
          command:
            pipenv install
      - run:
          name: run tests
          command:
            pipenv run python manage.py test
      - slack/notify:
          template: success_tagged_deploy_1
          event: pass
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  deploy_and_notify:
    jobs:
      - build:
          context: 
            - slack-secrets
