# Generated by Django 3.1 on 2020-09-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0002_holiday_holidaytype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together={('employee', 'leave_type')},
        ),
    ]
