# Generated by Django 3.1 on 2020-11-17 04:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holiday_holidaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_templates', to='leaves.holidaytype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Holiday Template',
                'verbose_name_plural': 'Holiday Templates',
            },
        ),
    ]
