# Generated by Django 3.1.1 on 2020-09-04 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holiday_holidaytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Count'),
        ),
    ]
